### ISSUE TITLE
 Better description of UDM in Planet conversion / output.

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/planet#3]
The new [file](https://github.com/radiantearth/stac-spec/tree/dev/extensions/file) extension has an example of using a [mapping object](https://github.com/radiantearth/stac-spec/tree/dev/extensions/file#mapping-object) to describe a cloud cover mask. Seems like it'd be useful to include that information about Planet's cloud mask.

Info at https://developers.planet.com/docs/data/udm-2/ - hrm, it looks like we use one band per class, instead of one band with all classes in it, so perhaps it'd be better to describe it with a 'bands' object, even if there are no common names. Regardless, it'd be good to have more description of the UDM asset in STAC.

## Additional notes

Note there have been people who have made single band UDM from Planet's multi-band asset. Could be cool to give an option in planet STAC conversion to reformat into that (arguably) more useful option. Especially if we make a 'band' description for UDM / QA like https://github.com/radiantearth/stac-spec/issues/977

## Migration

Migrated from https://github.com/stac-utils/stactools/issues/56.

**Comment by cholmes** [comment]
Closing this, as the mapping functionality is in flux. https://github.com/stac-extensions/file/issues/6

We probably should upgrade to more of the 'raster' extension stuff, but can make that its own issue.
